_target_: learned_qd.meta.meta_objective_qd.MetaObjective

select_key: ["fitness", "dominated_novelty"]
objective: qd_dns
op_task: "median"
op_norm: "zscore"
descriptor_size: ${task.descriptor_size}
population_size: ${evo.population.max_size}
